version: "0.4.{build}"
os: Visual Studio 2019
environment:
  My_TAG: "0.4.1"
configuration: Release
platform: x64
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        $env:My_TAG = $env:APPVEYOR_REPO_TAG_NAME
      }
      else
      {
        Update-AppveyorBuild -Version "0.4.$($env:APPVEYOR_BUILD_NUMBER)"
        $env:My_TAG = "0.4.$($env:APPVEYOR_BUILD_NUMBER)"
      }
before_build:
  - ps: nuget restore
build:
  project: WindowResizer.sln
after_build:
  - 7z a window_resizer_%My_TAG%.zip %APPVEYOR_BUILD_FOLDER%\WindowResizer\bin\x64\Release
artifacts:
  - path: window_resizer_$(My_TAG).zip
    name: WindowResizer_$(My_TAG)
deploy:
  release: $(My_TAG)
  description: WindowResizer_$(My_TAG)
  provider: GitHub
  auth_token:
    secure: UcxrOFRJ1elSazvncT3nPGT+xt+CjplLJ/D0avU9+Qru7HBVxUfUdoe0Iwcd412S
  artifact: window_resizer_$(My_TAG).zip
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
